name: Flutter CI

on:
  push:
    branches: [main, develop, feature/devops]
  pull_request:
    branches: [main, develop]
  workflow_dispatch: # erlaubt manuelles Starten im GitHub-UI

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Print directory & contents
      run: |
        pwd
        ls -la
        ls -la kundendokumentation_builder
        ls -la frontend_flutter

    - name: Install Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: stable
        flutter-version: 3.29.3
    - run: flutter --version

    - name: Load .env form Github Secret
      run: echo "${{ secrets.FRONTEND_ENV }}" > .env
      working-directory: frontend_flutter

    - name: Install dependencies
      run: flutter pub get
      working-directory: frontend_flutter

    - name: Flutter fix (optional vor Analyze)
      run: dart fix --apply
      working-directory: frontend_flutter

    - name: Analyze Code
      run: flutter analyze || true
      working-directory: frontend_flutter

    - name: Run tests (unit tests+widget tests)
      continue-on-error: true
      run: flutter test
      working-directory: frontend_flutter

    - name: Locate sdkmanager
      run: find /usr/local/lib/android/sdk -name sdkmanager

    - name: Accept Android SDK licenses
      run: yes | /usr/local/lib/android/sdk/cmdline-tools/latest/bin/sdkmanager --licenses

    - name: Build Android APK
      run: flutter build apk --release
      working-directory: frontend_flutter

    - name: Upload APK as artifact
      uses: actions/upload-artifact@v4
      with:
        name: android-apk
        path: frontend_flutter/build/app/outputs/flutter-apk/app-release.apk

